return {
	-- "folke/noice.nvim",
	-- event = "VeryLazy",
	-- dependencies = {
	--   "MunifTanjim/nui.nvim",
	--   "rcarriga/nvim-notify",
	-- },
	-- config = function()
	--   -- local notify = require("notify")
	--   -- notify.setup({
	--   --   stages = "static",
	--   --   timeout = 2000,
	--   --   render = "minimal",
	--   --   max_width = math.floor(vim.o.columns * 0.5),
	--   --   position = function()
	--   --     local row = math.floor(vim.o.lines * 0.4)
	--   --     local col = math.floor((vim.o.columns - (vim.o.columns * 0.5)) / 2)
	--   --     return { row = row, col = col }
	--   --   end,
	--   -- })
	--
	--   vim.notify = notify
	--
	--   require("noice").setup({
	--     notify = {
	--       enabled = true,
	--       view = "notify",
	--     },
	--     lsp = {
	--       progress = { enabled = true },
	--       override = {
	--         ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
	--         ["vim.lsp.util.stylize_markdown"] = true,
	--         ["cmp.entry.get_documentation"] = true,
	--       },
	--     },
	--     presets = {
	--       bottom_search = true,
	--       command_palette = false, -- disable top command layout
	--     },
	--     views = {
	--       cmdline_popup = {
	--         position = {
	--           row = -3,    -- 3 lines from bottom
	--           col = "50%", -- centered horizontally
	--         },
	--         size = {
	--           width = 60,
	--           height = "auto",
	--         },
	--         border = {
	--           style = "rounded",
	--         },
	--         win_options = {
	--           winhighlight = "Normal:Normal,FloatBorder:Title",
	--         },
	--       },
	--       messages = {
	--         border = {
	--           style = "double",
	--           padding = { 1, 1 },
	--         },
	--         win_options = {
	--           winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
	--         },
	--       },
	--     },
	--   })
	-- end,
}
